version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/WINDMEAL_FRONTEND
    overwrite: yes
#file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/WINDMEAL_FRONTEND
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
